version: '3'

services: 

  taborbizon: 
    build: app/
    container_name: taborbizon
    networks:
      - shared
  nginx: 
    image: nginx:1.18-alpine
    container_name: nginx
    networks:
        - shared
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"



    
networks:
  shared:
    name: taborbizon-network

